export const participantes = [
  {
    nombre: "Rene Silva",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/vmc555/",
    github: "https://github.com/rene3255",
    headshot: "/people/Rene.jpg",
  },
  {
    nombre: "Miguel Lopez",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/miguellopezmdev/",
    github: "https://github.com/mikelm2020",
    headshot: "/people/Migue.jpg",
  },
  {
    nombre: "Yeiner Parra",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/yeinerpb/",
    github: "https://github.com/yeinerpb",
    headshot: "/people/Yei.jpg",
  },
  {
    nombre: "Javier Brizuela",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/javier-brizuela1976/",
    github: "https://github.com/JavierBrizuela",
    headshot: "/people/Javi.jpg",
  },
  {
    nombre: "Daniel Ruiz",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/daniel-ruiz/",
    github: "https://github.com/ruizdani301",
    headshot: "/people/Dani.jpg",
  },
  {
    nombre: "Luis Guzmán",
    rol: "Backend",
    linkedin: "https://www.linkedin.com/in/dataluis/",
    github: "https://github.com/lumiguz",
    headshot: "/people/Luismi.jpg",
  },
  {
    nombre: "Alexander Ardila",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/jorge-ardila/",
    github: "https://github.com/jaardila-3",
    headshot: "/people/Alex.jpg",
  },
  {
    nombre: "Alejandro Álvarez",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/alejandro-alvarez-65030a240/",
    github: "https://github.com/alejou343",
    headshot: "/people/Ale.jpg",
  },
  {
    nombre: "Gabriel Mendoza",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/gabriel-mendoza-a1a077227/ ",
    github: "https://github.com/xzAnarchy",
    headshot: "/people/Gabi.jpg",
  },
  {
    nombre: "Jesús Vasquez",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/jesus-alberto-vasquez-ruiz-developer/",
    github: "https://github.com/AlbertoVasquezR",
    headshot: "/people/Jesus.jpg",
  },
  {
    nombre: "Antoni Perez",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/antoni-pérez",
    github: "https://github.com/antoniPrz",
    headshot: "/people/Anto.jpg",
  },
  {
    nombre: "Keiber Hernandez",
    rol: "Frontend",
    linkedin: "https://www.linkedin.com/in/keiber-hernandez/",
    github: "https://github.com/Keialex17",
    headshot: "/people/Kei.jpg",
  },
  {
    nombre: "Nuri Tasilla",
    rol: "Project Manager",
    linkedin: "https://www.linkedin.com/in/nurivictoria/",
    github: "https://github.com/NuriTasilla/",
    headshot: "/people/Nuri.jpg",
  },
];
